### ISSUE TITLE
修正点一覧

### ISSUE THREAD

**Issue by yoshi-koyama** [ThiriYadanar/CreateEmployee#2]
# README.mdを作りましょう。
書いてほしいこと

application.propertiesの設定変更部分
テーブルにデータを入れるためのinsert文

# pom.xml

hibernate-entitymanagerは必要ないです。

# new_employee.html

Sale -> Sales です。

**Comment by yoshi-koyama** [comment]
# CreateEmployeeApplication

@EnableJpaRepositoryは消して大丈夫です。

# application.properties

spring.datasource.password=

にしましょう。
ティリさんのパスワードは消しましょう！

# Employee

@Getterと@Setterのかわりに@Dataを使ってください。
そしてコンストラクタは削除しましょう。

@JsonFormat(shape=JsonFormat.Shape.STRING,pattern="yyyy-MM-dd")は必要ないですよね？

# EmployeeRepository

@Repositoryを付けましょう。

**Comment by ThiriYadanar** [comment]
> hibernate-entitymanagerは必要ないです。

これ消してEmployeeRegistration branch にアップロードしましたよね。

**Comment by ThiriYadanar** [comment]
全部修正してEmployeeRegistration branchにアップロードしました。

**Comment by ThiriYadanar** [comment]
> # README.mdを作りましょう。
> 書いてほしいこと
> 
> application.propertiesの設定変更部分
> テーブルにデータを入れるためのinsert文
> 
> # pom.xml
> hibernate-entitymanagerは必要ないです。
> 
> # new_employee.html
> Sale -> Sales です。

readme.md もアップロードしますか？

**Comment by yoshi-koyama** [comment]
#1 で対応済み！
